### ISSUE TITLE
Invoking implementations of methods with keyword args don't work on Ruby 3.2.0

### ISSUE THREAD

**Issue by Murphydbuffalo** [am-kantox/dry-behaviour#15]
Hi,

I think invoking methods defined by `defmethod`/`defimpl` with keyword arguments is not working correctly on Ruby 3.2.0.

I discovered this while trying to upgrade my app from 2.7 to 3.2 and was able to verify the failure by cloning the repo and running the tests.

Repro:
- Make sure you're using Ruby 3.2.0
- `git clone git@github.com:am-kantox/dry-behaviour.git`
- `cd dry-behavior`
- `bundle`
- `bundle exec rspec spec/dry/behaviour_spec.rb`

Failure: "works for default and keyword args (FAILED - 1)"
Error: "ArgumentError: wrong number of arguments (given 0, expected 1+)"

I'm seeing the same behavior in my app when trying to invoke a method with a positional and default keyword argument.

I'll see if I can locate the source of the issue and make a PR, but any guidance you can offer would be helpful.

Thanks!

**Comment by am-kantox** [comment]
Hi @Murphydbuffalo thanks for reporting it, I’ll take a look ASAP.

**Comment by am-kantox** [comment]
> Successfully registered gem: `dry-behaviour` (`0.12.1`)
